// Package render converts spec data into formatted document output (spec Section 8.2).
package render

import (
	"fmt"
	"strings"
	"unicode"

	"github.com/zyx-holdings/go-spec/internal/session"
)

// Markdown renders a session's answers as a structured CommonMark specification
// document. Sections for unselected feature areas are omitted entirely.
// Skipped optional questions are annotated with a TODO note.
func Markdown(sess *session.Session) string {
	b := &sectionBuilder{sess: sess}

	sections := buildSections(b)

	var sb strings.Builder
	writeHeader(&sb, sess)
	for i, sec := range sections {
		if i > 0 {
			sb.WriteString("\n---\n\n")
		}
		writeSection(&sb, sec)
	}
	return sb.String()
}

// buildSections assembles the ordered list of spec sections.
func buildSections(b *sectionBuilder) []Section {
	var sections []Section

	// Fixed sections 1–3
	sections = append(sections,
		b.buildProblemStatement(1),
		b.buildGoalsAndNonGoals(2),
		b.buildSystemOverview(3),
	)

	// One section per selected feature area (sections 4+)
	for i, fid := range b.sess.SelectedFeatures {
		sections = append(sections, b.buildFeatureSection(4+i, fid))
	}

	// Testing and Validation Matrix
	n := 4 + len(b.sess.SelectedFeatures)
	sections = append(sections, b.buildTestingMatrix(n))

	// Implementation Checklist
	sections = append(sections, b.buildImplementationChecklist(n+1))

	return sections
}

// writeHeader writes the document title and metadata preamble.
func writeHeader(sb *strings.Builder, sess *session.Session) {
	name := ""
	if ans, ok := sess.Answers["project_name"]; ok && !ans.Skipped {
		name = ans.Value.String()
	}
	if name == "" {
		name = "Untitled Project"
	}

	sb.WriteString(fmt.Sprintf("# %s — Specification\n\n", EscapeMarkdown(name)))
	sb.WriteString(fmt.Sprintf("**Generated by go-spec** · Session `%s`\n\n", sess.ID))
}

// writeSection writes a single numbered section to the string builder.
func writeSection(sb *strings.Builder, sec Section) {
	sb.WriteString(fmt.Sprintf("## %d. %s\n\n", sec.Number, sec.Title))
	for _, line := range sec.Lines {
		sb.WriteString(line)
		sb.WriteString("\n")
	}
	sb.WriteString("\n")
}

// WrapProse wraps a prose string at the given column width, breaking only at
// word boundaries. It returns one string per output line.
func WrapProse(text string, width int) []string {
	if len(text) <= width {
		return []string{text}
	}

	var lines []string
	words := strings.Fields(text)
	if len(words) == 0 {
		return []string{""}
	}

	current := words[0]
	for _, w := range words[1:] {
		if len(current)+1+len(w) > width {
			lines = append(lines, current)
			current = w
		} else {
			current += " " + w
		}
	}
	lines = append(lines, current)
	return lines
}

// EscapeMarkdown escapes characters that have special inline meaning in CommonMark.
// Only characters that are problematic inside prose spans are escaped:
// \ ` * _ [ ] ! |
// Characters like - . ( ) # + are left unescaped as they are not special in
// inline positions (they only matter at the start of a line or in specific
// structural positions that our renderer controls).
func EscapeMarkdown(s string) string {
	var sb strings.Builder
	for _, r := range s {
		switch r {
		case '\\', '`', '*', '_', '[', ']', '!', '|':
			sb.WriteRune('\\')
			sb.WriteRune(r)
		default:
			if unicode.IsPrint(r) || r == '\n' {
				sb.WriteRune(r)
			}
		}
	}
	return sb.String()
}
